### ISSUE TITLE
Connection refused 

### ISSUE THREAD

**Issue by duggienuggets** [SamPom100/UnusualVolumeDetector#3]
Hi there, love the idea of this! I installed all the requirements with the text file using VSCode, but now when I run market_scanner.py I get "connection refused" errors on lines that don't even exist like 117 for example. Any idea why that could be? Thank you!!!

**Comment by cogsworth37** [comment]
You should post a snippet of the error

**Comment by SujoyDutta** [comment]
```
>>> ftp = FTP("ftp.nasdaqtrader.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ftplib.py", line 117, in __init__
    self.connect(host)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ftplib.py", line 152, in connect
    source_address=self.source_address)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
```

**Comment by duggienuggets** [comment]
Mine ended up just being a restrictive firewall apparently. I tried it on another network and it works great! My error was not quite the same as the user above me posted, though. Thanks again for this tool.

**Comment by cogsworth37** [comment]
@SujoyDutta, This is indicitive of a slow network connection. You can reduce the amount of time the tool goes back in time. In the readme the author indicates there are 3 lines in which you can tweak to take less time. good luck!
